#pragma once

#include "baseTypes.h"


// Note: This file is used mostly to record specific pixel locations of the sprites used in Joust.


// Screen resolution
extern Coord2D SCREEN_RESOLUTION;
extern Bounds2D SCREEN_BOUNDS;


// Background Images
	// Title screen
extern const Coord2D BACKGROUND_TITLE_SIZE;
extern const Bounds2D BACKGROUND_TITLE_SPRITE_BOUNDS;
	// Wave background
extern const Coord2D BACKGROUND_WAVES_SIZE;
extern const Bounds2D BACKGROUND_WAVES_SPRITE_BOUNDS;
	// Hiscores image
extern const Coord2D BACKGROUND_HISCORES_SIZE;
extern const Bounds2D BACKGROUND_HISCORES_SPRITE_BOUNDS;


// Start locations
extern const Coord2D SPAWN_LOCATIONS[];
extern const uint8_t NUMBER_SPAWN_LOCATIONS;


// Player
extern const Coord2D PLAYER_SIZE_GROUNDED;
extern const Coord2D PLAYER_SIZE_FLYING;

extern const uint8_t PLAYER_ANIMATION_IDLE_NUM_FRAMES;
extern const float PLAYER_ANIMATION_IDLE_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D PLAYER_ANIMATION_IDLE_FIRST_SPRITE_BOUNDS;

extern const uint8_t PLAYER_ANIMATION_RUNNING_NUM_FRAMES;
extern const float PLAYER_ANIMATION_RUNNING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D PLAYER_ANIMATION_RUNNING_FIRST_SPRITE_BOUNDS;

extern const uint8_t PLAYER_ANIMATION_RUNSLOWING_NUM_FRAMES;
extern const float PLAYER_ANIMATION_RUNSLOWING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D PLAYER_ANIMATION_RUNSLOWING_FIRST_SPRITE_BOUNDS;

extern const uint8_t PLAYER_ANIMATION_FLYING_NUM_FRAMES;
extern const float PLAYER_ANIMATION_FLYING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D PLAYER_ANIMATION_FLYING_FIRST_SPRITE_BOUNDS;


// Enemies
extern const Coord2D ENEMY_SIZE_GROUNDED;
extern const Coord2D ENEMY_SIZE_FLYING;

	// Bounder
extern const uint8_t ENEMY_BOUNDER_ANIMATION_IDLE_NUM_FRAMES;
extern const float ENEMY_BOUNDER_ANIMATION_IDLE_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_BOUNDER_ANIMATION_IDLE_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_BOUNDER_ANIMATION_RUNNING_NUM_FRAMES;
extern const float ENEMY_BOUNDER_ANIMATION_RUNNING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_BOUNDER_ANIMATION_RUNNING_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_BOUNDER_ANIMATION_RUNSLOWING_NUM_FRAMES;
extern const float ENEMY_BOUNDER_ANIMATION_RUNSLOWING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_BOUNDER_ANIMATION_RUNSLOWING_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_BOUNDER_ANIMATION_FLYING_NUM_FRAMES;
extern const float ENEMY_BOUNDER_ANIMATION_FLYING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_BOUNDER_ANIMATION_FLYING_FIRST_SPRITE_BOUNDS;

	// Hunter
extern const uint8_t ENEMY_HUNTER_ANIMATION_IDLE_NUM_FRAMES;
extern const float ENEMY_HUNTER_ANIMATION_IDLE_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_HUNTER_ANIMATION_IDLE_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_HUNTER_ANIMATION_RUNNING_NUM_FRAMES;
extern const float ENEMY_HUNTER_ANIMATION_RUNNING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_HUNTER_ANIMATION_RUNNING_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_HUNTER_ANIMATION_RUNSLOWING_NUM_FRAMES;
extern const float ENEMY_HUNTER_ANIMATION_RUNSLOWING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_HUNTER_ANIMATION_RUNSLOWING_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_HUNTER_ANIMATION_FLYING_NUM_FRAMES;
extern const float ENEMY_HUNTER_ANIMATION_FLYING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_HUNTER_ANIMATION_FLYING_FIRST_SPRITE_BOUNDS;

	// Shadow Lord
extern const uint8_t ENEMY_SHADOWLORD_ANIMATION_IDLE_NUM_FRAMES;
extern const float ENEMY_SHADOWLORD_ANIMATION_IDLE_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_SHADOWLORD_ANIMATION_IDLE_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_SHADOWLORD_ANIMATION_RUNNING_NUM_FRAMES;
extern const float ENEMY_SHADOWLORD_ANIMATION_RUNNING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_SHADOWLORD_ANIMATION_RUNNING_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_SHADOWLORD_ANIMATION_RUNSLOWING_NUM_FRAMES;
extern const float ENEMY_SHADOWLORD_ANIMATION_RUNSLOWING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_SHADOWLORD_ANIMATION_RUNSLOWING_FIRST_SPRITE_BOUNDS;

extern const uint8_t ENEMY_SHADOWLORD_ANIMATION_FLYING_NUM_FRAMES;
extern const float ENEMY_SHADOWLORD_ANIMATION_FLYING_PIXELS_BETWEEN_FRAMES;
extern const Bounds2D ENEMY_SHADOWLORD_ANIMATION_FLYING_FIRST_SPRITE_BOUNDS;


// Collision Boxes
extern const Coord2D COLLBOX_BOT_TL;
extern const Coord2D COLLBOX_BOT_BR;

extern const Coord2D COLLBOX_MIDLEFT_TL;
extern const Coord2D COLLBOX_MIDLEFT_BR;

extern const Coord2D COLLBOX_MID_TL;
extern const Coord2D COLLBOX_MID_BR;

extern const Coord2D COLLBOX_MIDRIGHT_TL;
extern const Coord2D COLLBOX_MIDRIGHT_BR;

extern const Coord2D COLLBOX_MIDRIGHT_WRAP_TL;
extern const Coord2D COLLBOX_MIDRIGHT_WRAP_BR;

extern const Coord2D COLLBOX_TOPLEFT_TL;
extern const Coord2D COLLBOX_TOPLEFT_BR;

extern const Coord2D COLLBOX_TOPMID_TL;
extern const Coord2D COLLBOX_TOPMID_BR;

extern const Coord2D COLLBOX_TOPRIGHT_TL;
extern const Coord2D COLLBOX_TOPRIGHT_BR;


// Number Sprites
extern const uint8_t NUMBER_SPRITE_PIXELS_BETWEEN_SPRITES;

extern const Coord2D NUMBER_SPRITE_YELLOW_0_TL;
extern const Coord2D NUMBER_SPRITE_YELLOW_0_BR;

extern const Coord2D NUMBER_SPRITE_BLUE_0_TL;
extern const Coord2D NUMBER_SPRITE_BLUE_0_BR;

extern const Coord2D NUMBER_SPRITE_WHITE_0_TL;
extern const Coord2D NUMBER_SPRITE_WHITE_0_BR;


// Score Board Location
extern const Coord2D SCOREBOARD_TL;
extern const Coord2D SCOREBOARD_BR;


// Lives Display Location
extern const Coord2D LIVES_DISPLAY_TL;
extern const Coord2D LIVES_DISPLAY_BR;


// Spawn Locations
extern const Bounds2D SPAWN_BOTTOM_LOCATION;
extern const Bounds2D SPAWN_LEFT_LOCATION;
extern const Bounds2D SPAWN_RIGHT_LOCATION;
extern const Bounds2D SPAWN_TOP_LOCATION;


// Animation Timers
extern const uint32_t ANIMATION_SPEED_FLAP;
extern const uint32_t ANIMATION_SPEED_RUN;


// Word Sprites
extern Coord2D WORDS_WAVE_SIZE;
extern const Bounds2D WORDS_SPRITE_WAVE;

extern Coord2D WORDS_PREPARE_SIZE;
extern const Bounds2D WORDS_SPRITE_PREPARE;

extern Coord2D WORDS_GAMEOVER_SIZE;
extern const Bounds2D WORDS_SPRITE_GAMEOVER;

extern Coord2D WORDS_BUZZARD_SIZE;
extern const Bounds2D WORDS_SPRITE_BUZZARD;

extern Coord2D WORDS_SURVIVAL_SIZE;
extern const Bounds2D WORDS_SPRITE_SURVIVAL;

extern Coord2D WORDS_EGGWAVE_SIZE;
extern const Bounds2D WORDS_SPRITE_EGGWAVE;

extern Coord2D WORDS_BEWARE_SIZE;
extern const Bounds2D WORDS_SPRITE_BEWARE;

typedef enum wordsIndex_t
{
	WORDS_WAVE,
	WORDS_PREPARE,
	WORDS_GAMEOVER,
	WORDS_BUZZARD,
	WORDS_SURVIVAL,
	WORDS_EGGWAVE,
	WORDS_BEWARE,

	WORDS_COUNT
} WordsIndex;
